"""Command line: ``pumpwatch demo | scan | backtest | verify-log``."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .audit import AuditLog, config_fingerprint
from .backtest import calibrate_and_test, load_cases, render_markdown
from .config import Config
from .engine import Engine
from .io import DataError, load_dir, save_cases, save_dir
from .synth import SynthSpec, generate

SYNTH_NOTE = (
    "SYNTHETIC data generated by pumpwatch.synth. These numbers only show that the engine "
    "and backtest are wired correctly. They say NOTHING about real-world accuracy."
)


def _config(args) -> Config:
    cfg = Config()
    if getattr(args, "threshold", None) is not None:
        cfg = cfg.with_(alert_threshold=args.threshold)
    return cfg


def cmd_demo(args) -> int:
    data, cases = generate(SynthSpec(seed=args.seed))
    out = Path(args.out)
    save_dir(data, out / "data")
    save_cases(cases, out / "cases.csv")
    engine = Engine(_config(args))
    runs = engine.run(data)
    report = calibrate_and_test(engine, runs, cases)
    md = render_markdown(report, SYNTH_NOTE)
    (out / "report.md").write_text(md, encoding="utf-8")
    print(md)
    print(f"\nwrote {out}/data, {out}/cases.csv and {out}/report.md")
    return 0


def cmd_scan(args) -> int:
    data = load_dir(args.data)
    engine = Engine(_config(args))
    runs = engine.run(data)
    alerts = sorted((a for r in runs.values() for a in r.alerts), key=lambda a: (a.day, -a.score))
    if args.since:
        alerts = [a for a in alerts if a.day.isoformat() >= args.since]
    log = AuditLog(args.log) if args.log else None
    fp = config_fingerprint(engine.cfg)
    for a in alerts:
        if log:
            log.append(a, __version__, fp)
        print(json.dumps(a.to_dict(), ensure_ascii=False))
    print(f"{len(alerts)} alert(s) across {len(runs)} ticker(s)", file=sys.stderr)
    return 0


def cmd_backtest(args) -> int:
    data = load_dir(args.data)
    cases = load_cases(args.cases)
    engine = Engine(_config(args))
    runs = engine.run(data)
    missing = sorted({c.ticker for c in cases} - set(runs))
    if missing:
        print(f"warning: no price data for {len(missing)} case ticker(s): {', '.join(missing)}", file=sys.stderr)
    report = calibrate_and_test(engine, runs, cases, max_false_per_catch=args.max_false)
    md = render_markdown(report, args.note or f"loaded from {args.data}")
    if args.out:
        Path(args.out).write_text(md, encoding="utf-8")
    print(md)
    return 0


def cmd_verify(args) -> int:
    res = AuditLog(args.log).verify()
    if res.ok:
        print(f"OK: {res.records} record(s), chain intact")
        return 0
    print(f"TAMPERED: line {res.broken_at}: {res.reason}")
    return 1


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="pumpwatch", description="Pump-and-dump early warning engine")
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="cmd", required=True)

    d = sub.add_parser("demo", help="generate synthetic data and run a backtest on it")
    d.add_argument("--out", default="out/demo")
    d.add_argument("--seed", type=int, default=7)
    d.add_argument("--threshold", type=float)
    d.set_defaults(func=cmd_demo)

    s = sub.add_parser("scan", help="score a data directory and print alerts as JSON lines")
    s.add_argument("data")
    s.add_argument("--since", help="only print alerts on or after YYYY-MM-DD")
    s.add_argument("--log", help="append alerts to this hash-chained audit log")
    s.add_argument("--threshold", type=float)
    s.set_defaults(func=cmd_scan)

    b = sub.add_parser("backtest", help="calibrate on half the cases, report on the other half")
    b.add_argument("data")
    b.add_argument("cases")
    b.add_argument("--out")
    b.add_argument("--note")
    b.add_argument("--max-false", type=float, default=5.0)
    b.add_argument("--threshold", type=float)
    b.set_defaults(func=cmd_backtest)

    v = sub.add_parser("verify-log", help="check an audit log has not been altered")
    v.add_argument("log")
    v.set_defaults(func=cmd_verify)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except DataError as exc:
        print(f"data error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
